"""Train the CRNN DataMatrix recognition model.

Trains a CRNN with CTC loss on synthetic (image, content-string) pairs
generated by ``training/prepare_recognition_dataset.py``.

Usage::

    # 1. Generate the recognition dataset first:
    python -m training.prepare_recognition_dataset --num-images 5000

    # 2. Train the recogniser (run on a GPU machine, NOT on Raspberry Pi):
    python -m training.train_recognizer \\
        --data training/data/recognition \\
        --epochs 100 \\
        --device cuda

Requirements (training machine only)::

    pip install torch torchvision albumentations pylibdmtx

Checkpoint saved to::

    runs/recognize/<name>/best.pt

The ``best.pt`` file is later exported to ONNX by
``training/export_recognizer.py``.
"""

import argparse
import os
from pathlib import Path

import cv2
import numpy as np
import torch
import torch.nn as nn
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import DataLoader, Dataset

from .models.crnn import CRNN, IMG_H, IMG_W, VOCAB_SIZE, build_vocab, char_to_idx


# ──────────────────────────────────────────────────────────────────────────────
# Dataset
# ──────────────────────────────────────────────────────────────────────────────


class DataMatrixRecognitionDataset(Dataset):
    """PyTorch Dataset for (DataMatrix image, content label) pairs.

    Expects the layout produced by ``prepare_recognition_dataset.py``::

        data_dir/
        ├── images/train/   or   images/val/
        └── labels_train.txt     labels_val.txt

    Labels file format: one ``<filename>\\t<content>`` per line.
    """

    def __init__(
        self,
        data_dir: str,
        split: str = "train",
        vocab: list[str] | None = None,
        augment: bool = True,
    ) -> None:
        self._img_dir = os.path.join(data_dir, "images", split)
        self._vocab = vocab or build_vocab()
        self._augment = augment and (split == "train")

        label_file = os.path.join(data_dir, f"labels_{split}.txt")
        self._samples: list[tuple[str, str]] = []
        with open(label_file, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if "\t" not in line:
                    continue
                filename, content = line.split("\t", 1)
                self._samples.append((filename, content))

    def __len__(self) -> int:
        return len(self._samples)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor, int]:
        filename, content = self._samples[idx]
        img_path = os.path.join(self._img_dir, filename)

        gray = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if gray is None:
            # Fallback: blank image
            gray = np.zeros((IMG_H, IMG_W), dtype=np.uint8)
        else:
            gray = cv2.resize(gray, (IMG_W, IMG_H), interpolation=cv2.INTER_AREA)

        if self._augment:
            gray = self._apply_augmentation(gray)

        # (1, H, W) float32 in [0, 1]
        tensor = torch.from_numpy(gray.astype(np.float32) / 255.0).unsqueeze(0)

        # Encode label as index sequence (ignoring blank=0)
        label_indices = [
            char_to_idx(ch, self._vocab)
            for ch in content
            if char_to_idx(ch, self._vocab) != 0
        ]
        label_tensor = torch.tensor(label_indices, dtype=torch.long)
        return tensor, label_tensor, len(label_indices)

    @staticmethod
    def _apply_augmentation(image: np.ndarray) -> np.ndarray:
        """Lightweight NumPy augmentation (no extra dependencies)."""
        if np.random.rand() < 0.5:
            factor = np.random.uniform(0.7, 1.3)
            image = np.clip(image.astype(np.float32) * factor, 0, 255).astype(np.uint8)
        if np.random.rand() < 0.3:
            ksize = np.random.choice([3, 5])
            image = cv2.GaussianBlur(image, (ksize, ksize), 0)
        if np.random.rand() < 0.3:
            noise = np.random.normal(0, np.random.uniform(5, 20), image.shape).astype(np.int16)
            image = np.clip(image.astype(np.int16) + noise, 0, 255).astype(np.uint8)
        return image


def _collate_fn(
    batch: list[tuple[torch.Tensor, torch.Tensor, int]],
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """Custom collate that pads variable-length label sequences."""
    images, labels, label_lengths = zip(*batch)

    images_tensor = torch.stack(images, dim=0)  # (B, 1, H, W)
    label_lengths_tensor = torch.tensor(label_lengths, dtype=torch.long)
    labels_concat = torch.cat(labels, dim=0)  # concatenated flat labels for CTC
    return images_tensor, labels_concat, label_lengths_tensor


# ──────────────────────────────────────────────────────────────────────────────
# Evaluation
# ──────────────────────────────────────────────────────────────────────────────


def _decode_predictions(
    log_probs: torch.Tensor, vocab: list[str]
) -> list[str]:
    """Greedy CTC decode a batch of log-softmax outputs.

    Args:
        log_probs: (T, B, vocab_size).
        vocab:     Vocabulary from build_vocab().

    Returns:
        List of decoded strings, one per batch element.
    """
    preds = log_probs.argmax(dim=-1)  # (T, B)
    results: list[str] = []
    for b in range(preds.shape[1]):
        seq = preds[:, b].cpu().tolist()
        chars: list[str] = []
        prev = -1
        for p in seq:
            if p != prev:
                if p != 0:
                    chars.append(vocab[p])
                prev = p
        results.append("".join(chars))
    return results


def evaluate(
    model: CRNN,
    loader: DataLoader,
    vocab: list[str],
    device: torch.device,
) -> tuple[float, float]:
    """Return (mean CTC loss, exact-string accuracy) on *loader*."""
    model.eval()
    ctc_loss = nn.CTCLoss(blank=0, reduction="mean", zero_infinity=True)
    total_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels, label_lengths in loader:
            images = images.to(device)
            log_probs = model(images)  # (T, B, V)
            T, B, _ = log_probs.shape
            input_lengths = torch.full((B,), T, dtype=torch.long)
            loss = ctc_loss(log_probs.cpu(), labels, input_lengths, label_lengths)
            total_loss += loss.item()

            decoded = _decode_predictions(log_probs, vocab)
            # Reconstruct ground-truth strings from concatenated labels
            offset = 0
            for i, length in enumerate(label_lengths.tolist()):
                gt_indices = labels[offset : offset + length].tolist()
                gt = "".join(vocab[idx] for idx in gt_indices if idx != 0)
                offset += length
                if decoded[i] == gt:
                    correct += 1
                total += 1

    mean_loss = total_loss / max(1, len(loader))
    accuracy = correct / max(1, total)
    return mean_loss, accuracy


# ──────────────────────────────────────────────────────────────────────────────
# Training loop
# ──────────────────────────────────────────────────────────────────────────────


def train(args: argparse.Namespace) -> None:
    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    print(f"Training on: {device}")

    vocab = build_vocab()

    train_dataset = DataMatrixRecognitionDataset(args.data, split="train", vocab=vocab)
    val_dataset = DataMatrixRecognitionDataset(args.data, split="val", vocab=vocab, augment=False)

    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch,
        shuffle=True,
        num_workers=args.workers,
        collate_fn=_collate_fn,
        pin_memory=(device.type == "cuda"),
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=args.batch,
        shuffle=False,
        num_workers=args.workers,
        collate_fn=_collate_fn,
    )

    model = CRNN(vocab_size=VOCAB_SIZE, hidden_size=args.hidden).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    scheduler = CosineAnnealingLR(optimizer, T_max=args.epochs, eta_min=1e-6)
    ctc_loss = nn.CTCLoss(blank=0, reduction="mean", zero_infinity=True)

    # Output directory
    run_dir = Path(args.project) / args.name
    run_dir.mkdir(parents=True, exist_ok=True)
    weights_dir = run_dir / "weights"
    weights_dir.mkdir(exist_ok=True)

    best_val_acc = 0.0
    patience_counter = 0

    print(f"Train samples: {len(train_dataset)}  |  Val samples: {len(val_dataset)}")
    print(f"Saving runs to: {run_dir}")

    for epoch in range(1, args.epochs + 1):
        model.train()
        epoch_loss = 0.0

        for images, labels, label_lengths in train_loader:
            images = images.to(device)
            log_probs = model(images)  # (T, B, V)
            T, B, _ = log_probs.shape
            input_lengths = torch.full((B,), T, dtype=torch.long)

            loss = ctc_loss(log_probs.cpu(), labels, input_lengths, label_lengths)
            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
            optimizer.step()
            epoch_loss += loss.item()

        scheduler.step()
        mean_train_loss = epoch_loss / max(1, len(train_loader))

        if epoch % args.val_interval == 0 or epoch == args.epochs:
            val_loss, val_acc = evaluate(model, val_loader, vocab, device)
            lr_now = scheduler.get_last_lr()[0]
            print(
                f"Epoch {epoch:03d}/{args.epochs}  "
                f"train_loss={mean_train_loss:.4f}  "
                f"val_loss={val_loss:.4f}  val_acc={val_acc:.4f}  lr={lr_now:.2e}"
            )

            if val_acc > best_val_acc:
                best_val_acc = val_acc
                patience_counter = 0
                checkpoint = {
                    "epoch": epoch,
                    "model_state_dict": model.state_dict(),
                    "optimizer_state_dict": optimizer.state_dict(),
                    "val_acc": val_acc,
                    "vocab_size": VOCAB_SIZE,
                    "hidden_size": args.hidden,
                }
                torch.save(checkpoint, weights_dir / "best.pt")
                print(f"  ✓ New best — saved to {weights_dir / 'best.pt'}")
            else:
                patience_counter += 1
                if patience_counter >= args.patience:
                    print(f"Early stopping (no improvement for {args.patience} val checks).")
                    break

        if epoch % args.save_period == 0:
            torch.save(
                {"epoch": epoch, "model_state_dict": model.state_dict()},
                weights_dir / f"epoch_{epoch:03d}.pt",
            )

    print(f"\nTraining complete.  Best val accuracy: {best_val_acc:.4f}")
    print(f"Best model: {weights_dir / 'best.pt'}")


# ──────────────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(description="Train CRNN for DataMatrix recognition")
    parser.add_argument("--data", type=str, default="training/data/recognition",
                        help="Path to recognition dataset (default: training/data/recognition)")
    parser.add_argument("--epochs", type=int, default=100,
                        help="Max training epochs (default: 100)")
    parser.add_argument("--batch", type=int, default=64,
                        help="Batch size (default: 64)")
    parser.add_argument("--lr", type=float, default=1e-3,
                        help="Initial learning rate (default: 1e-3)")
    parser.add_argument("--hidden", type=int, default=256,
                        help="BiLSTM hidden size (default: 256)")
    parser.add_argument("--workers", type=int, default=4,
                        help="DataLoader worker processes (default: 4)")
    parser.add_argument("--device", type=str, default="cuda",
                        help="Training device: 'cuda' or 'cpu' (default: cuda)")
    parser.add_argument("--patience", type=int, default=15,
                        help="Early-stopping patience in val intervals (default: 15)")
    parser.add_argument("--val-interval", type=int, default=5,
                        help="Validate every N epochs (default: 5)")
    parser.add_argument("--save-period", type=int, default=20,
                        help="Save checkpoint every N epochs (default: 20)")
    parser.add_argument("--project", type=str, default="runs/recognize",
                        help="Project directory (default: runs/recognize)")
    parser.add_argument("--name", type=str, default="datamatrix_crnn_v1",
                        help="Run name (default: datamatrix_crnn_v1)")
    args = parser.parse_args()

    train(args)


if __name__ == "__main__":
    main()
